In [1]:
import pandas as pd

In [2]:
pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
# From dictionary
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
 
# From list of lists
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])

In [5]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.head()  	# First 5 rows
df.tail()  	# Last 5 rows
df.info()  	# Info about DataFrame
df.describe()  # Summary statistics

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [7]:
# Column selection
df['Name']
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [8]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [9]:
df.loc[0]
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [10]:
df[df['Age'] > 25]  # Rows where Age > 25

  Name  Age
1  Bob   30

In [11]:
df['Gender'] = ['F', 'M']  # Add new column
df.drop('Age', axis=1, inplace=True)  # Remove column

In [12]:
df

    Name Gender
0  Alice      F
1    Bob      M

In [13]:
df.isnull()
df.dropna()
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [14]:
df.groupby('Gender')['Age'].mean()

KeyError: 'Column not found: Age'

In [15]:
df

    Name Gender
0  Alice      F
1    Bob      M

In [16]:
# Merge two DataFrames
pd.merge(df1, df2, on='key')

NameError: name 'df1' is not defined

In [17]:
df

    Name Gender
0  Alice      F
1    Bob      M

In [18]:
df1.join(df2)

NameError: name 'df1' is not defined

In [19]:
df = pd.read_csv('data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [20]:
data = {
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30],
    'Gender': ['F', 'M']
}

df = pd.DataFrame(data)
df.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [21]:
df1 = pd.DataFrame({'key': [1, 2], 'Name': ['Alice', 'Bob']})
df2 = pd.DataFrame({'key': [1, 2], 'Age': [25, 30]})

pd.merge(df1, df2, on='key')

   key   Name  Age
0    1  Alice   25
1    2    Bob   30

In [22]:
df1 = pd.DataFrame({'key': [1, 2], 'Name': ['Alice', 'Bob']})
df2 = pd.DataFrame({'key': [1, 2], 'Age': [25, 30]})

pd.merge(df1, df2, on='key')

   key   Name  Age
0    1  Alice   25
1    2    Bob   30

In [23]:
df = pd.read_csv('data.csv')
df.to_csv('output.csv', index=False)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [24]:
df.sort_values('Age')
df['Age'].apply(lambda x: x + 1)
df['Name'].unique()
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64